### PR TITLE
fix: Replace use of eval with Function constructor on sandbox

### PR DESCRIPTION
**Pull request by munshkr**
This fixes minification issues on Rollup/esbuild (and Vite).

I'm not 100% sure I'm not breaking something here, but AFAIK it works the same. @ojack do you think this would work?

### CODE REVIEW

**Comment by ojack** [comment]
Oooh interesting, will test! Feel free to bother me if I don't respond by
next week :)

**Comment by munshkr** [comment]
Sure! thanks :)

**Comment by munshkr** [comment]
@ojack were you able to give it a try? I can do some testing on the hydra editor this weekend maybe

**Comment by ojack** [comment]
@munshkr was just trying at the link but was not able to see any visuals --- any ideas? otherwise have not had a chance to try!

**Comment by ojack** [comment]
I think actually the sandbox eval isn't being used anywhere?
 I was trying to create the sandbox as a way to avoid global eval(), but now looking at it, I don't think it is even doing anything in hydra-synth as most eval happens within the editor context. I feel like I am missing something though. tagging @ritchse @micuat just in case. but in the meantime will go ahead and merge.

**Comment by ojack** [comment]
Speaking of which, @munshkr how do you deal with eval() in flok? I think this is more relevant to the editor, but wondering whether there is a better way

**Comment by munshkr** [comment]
> I think actually the sandbox eval isn't being used anywhere? I was trying to create the sandbox as a way to avoid global eval(), but now looking at it, I don't think it is even doing anything in hydra-synth as most eval happens within the editor context. I feel like I am missing something though. tagging @ritchse @micuat just in case. but in the meantime will go ahead and merge.

Ahh I thought the editor used that `sandbox.eval`! I'm using it on flok, but yeah it's basically the same global eval...

> Speaking of which, @munshkr how do you deal with eval() in flok? I think this is more relevant to the editor, but wondering whether there is a better way

Right now in the new version of flok, I'm calling the `eval` function on HydraSynth class, which I think uses the sandbox (and that's why I bumped into this issue and sent this small fix).

I came up with this from [this article](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval#using_the_function_constructor), which explains some alternatives to `eval`. Looks like using `Function` constructor is a bit better than `eval`, not only to avoid these kinds of issues with minifiers, but also it allows you to run in strict mode and if you want, define or override some globals with custom function/classes inside the evaluation context. I've taken advantage of this on [hydra-p5](https://github.com/munshkr/hydra-p5/blob/91002fd615384384e0c479554691b859e2766cd1/index.js#L13-L24), for having all p5 functions as globals only within the `draw` callback function:

Instead of this:

```js
p5src(s0)
  .draw(p5 => {
    p5.clear()
    p5.rect(p5.mouseX, p5.mouseY, 300, 300)
  })
  .out()
```

You can do:

```js
p5src(s0)
  .drawP(_ => {
    clear()
    rect(mouseX, mouseY, 300, 300)
  })
  .out()

// `clear`, `rect` are undefined here...
```

I haven't really thought of the potential misuses and problems of not evaluating inside a sandbox...

**Comment by ojack** [comment]
Ohh cool! I hadnt seen hydra-p5, exciting!

**Comment by ojack** [comment]
Alsooo curious to see what direction you are heading lately with flok! I
have been wanting to publish a cm6 version of hydra's editor (i have a
local one but the code is terribly messy) and also to separate out the
editor as its own package so that people can use it in different projects.
Some things that have been exciting to me are exploring autocomplete
possibilities and also better error handling by reporting the line number
and highlighting in the editor. Wondering whether some of this work
overlaps with what you are working on in flok.

**Comment by munshkr** [comment]
> Alsooo curious to see what direction you are heading lately with flok! I have been wanting to publish a cm6 version of hydra's editor (i have a local one but the code is terribly messy) and also to separate out the editor as its own package so that people can use it in different projects. Some things that have been exciting to me are exploring autocomplete possibilities and also better error handling by reporting the line number and highlighting in the editor. Wondering whether some of this work overlaps with what you are working on in flok.

Yes, definitely! 😄  I'm reimplementing Flok based on Codemirror 6, and this time I'm trying to decouple everything as much as possible too, with the intention to build these reusable components/extensions for the community. For example, [this package](https://github.com/munshkr/flok/tree/flok-next/packages/cm-eval) is supposed to implement a general code evaluation feature for Codemirror editors, with line/block/document evaluation and flash highlighting. It's still a bit coupled to flok, but my intention is to make it agnostic, so it can be used in non-flok projects.

I know there's a lot of work done at [text.management](https://github.com/mindofmatthew/text.management) and [your project](https://github.com/ojack/hydra-editor-cm6), it'd be great if we can manage to build a common ground and collaborate!

**Comment by msawired** [comment]
I noticed that this update in commit #136 caused Hydra to throw a cross-origin error if the Hydra is loaded in a cross-origin iframe. Such as when it is used on OpenProcessing.org, CodePen, etc. I assume that would also be true if embedded in a blog etc. Some examples:
https://codepen.io/msawired/pen/dygWmPV
https://openprocessing.org/sketch/1879169

The CORS error details are visible on native browser console.

I am guessing this has something to do with the scoping of eval vs. Func() and accessing parent window.

**Comment by micuat** [comment]
I'm also seeing an error due to iframe after this commit and was about to submit an issue - thanks for reporting @msawired

**Comment by ojack** [comment]
Ohh interesting, thank you for reporting! Interesting because ([here](https://uniquemagicalbrowserobjects.com/))  hydra is running in several iframes, but seems to still work fine: 

Anyway, I would like to revert to an earlier version until we find a way for this to work. 

Any thoughts on how best to revert an npm module?

**Comment by msawired** [comment]
@ojack, those iframes in the link you sent are all from the same domain as the parent. The CORS issue happens when iframe domains (or ports) are different from the parent.

**Comment by ojack** [comment]
Okay, should be updated.

**Comment by munshkr** [comment]
Oops :( good catch, forgot completely of the iframe use case.

**Comment by ojack** [comment]
I still feel like there should be a way to make both things work...I just
haven't had any time to work on this yet.

**Comment by msawired** [comment]
Can anyone explain little why parent access needed or used for? I have some experience working with iframes from OpenProcessing, I can try to look into it. Maybe just a simple check can be added if parent access is allowed.

**Pull request merged**
